# Generated by Django 6.0.1 on 2026-02-09 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0003_alter_inscription_amount_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Montant demandé ou payé (FCFA)')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('bank_transfer', 'Virement bancaire')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Référence (reçu, OM, virement, agent, etc.)', max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la demande')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date de validation du paiement', null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inscriptions.inscription')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['method'], name='payments_pa_method_70cfb8_idx'), models.Index(fields=['requested_at'], name='payments_pa_request_a7abb9_idx')],
            },
        ),
    ]
