# Generated by Django 6.0.1 on 2026-02-09 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0002_inscription_amount_due_inscription_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Montant payé (en FCFA)')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('bank_transfer', 'Virement bancaire')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='validated', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Référence du paiement (reçu, OM, virement, etc.)', max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inscriptions.inscription')),
            ],
            options={
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['method'], name='payments_pa_method_70cfb8_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['paid_at'], name='payments_pa_paid_at_b40014_idx')],
            },
        ),
    ]
