# Generated by Django 6.0.1 on 2026-02-07 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        ('inscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Frais d’inscription, Tranche 1, Tranche 2', max_length=255)),
                ('fee_type', models.CharField(choices=[('registration', 'Frais d’inscription'), ('tuition', 'Frais de scolarité'), ('other', 'Autres frais')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordre logique de paiement')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Obligatoire pour activer l’inscription')),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='formations.programme')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('programme', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_override', models.DecimalField(blank=True, decimal_places=2, help_text='Montant exceptionnel (réduction, bourse, arrangement)', max_digits=10, null=True)),
                ('is_settled', models.BooleanField(default=False, help_text='Frais totalement réglé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='inscriptions.enrollment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.feetemplate')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('enrollment', 'template')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('bank', 'Virement bancaire'), ('online', 'Paiement en ligne')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Reçu, référence Mobile Money, transaction bancaire', max_length=150)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.fee')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
