# Generated by Django 6.0.1 on 2026-02-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='amount_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant exceptionnel (réduction, arrangement)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='payments.feetemplate'),
        ),
        migrations.AlterField(
            model_name='feetemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Désactiver sans supprimer'),
        ),
        migrations.AlterField(
            model_name='feetemplate',
            name='label',
            field=models.CharField(help_text='Ex : Frais d’inscription, Tranche Janvier', max_length=255),
        ),
    ]
