# Generated by Django 6.0.1 on 2026-02-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_alter_inscription_amount_due_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_paid_at_b40014_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=1, help_text='Date de création de la demande'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Date de validation du paiement', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Montant demandé ou payé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence (reçu, OM, virement, agent, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['requested_at'], name='payments_pa_request_a7abb9_idx'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
    ]
