# Generated by Django 6.0.1 on 2026-02-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0008_alter_inscription_amount_due'),
        ('payments', '0004_paymentagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='payments.paymentagent')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='inscriptions.inscription')),
            ],
        ),
    ]
