# Generated by Django 6.0.1 on 2026-02-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_cashpaymentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentagent'),
        ),
    ]
