# Generated by Django 6.0.1 on 2026-02-07 17:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: 2024-2025', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Année académique en cours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, help_text='Généré automatiquement après validation', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('suspended', 'Suspendue'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Observations administratives internes')),
                ('is_active', models.BooleanField(default=False, help_text="Autorise l'accès à la plateforme pédagogique")),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('finalized_at', models.DateTimeField(blank=True, help_text="Date de finalisation par le candidat ou l'administration", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='inscriptions.academicyear')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='admissions.application')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
