# Generated by Django 6.0.1 on 2026-02-09 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('created', 'Créée'), ('active', 'Active'), ('suspended', 'Suspendue')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inscription', to='admissions.candidature')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
