# Generated by Django 6.0.1 on 2026-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text="Date d'activation après paiement", null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='matricule',
            field=models.CharField(blank=True, help_text='Généré automatiquement après activation', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée administrativement'), ('suspended', 'Suspendue'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
