# Generated by Django 6.0.1 on 2026-02-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_inscription_amount_due_inscription_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='amount_due',
            field=models.PositiveIntegerField(default=0, help_text='Montant total à payer pour l’inscription (FCFA)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0, help_text='Montant déjà payé (FCFA)'),
        ),
    ]
