# Generated by Django 6.0.1 on 2026-02-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_alter_inscription_amount_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
