# Generated by Django 6.0.1 on 2026-02-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_inscription_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='amount_due',
            field=models.PositiveIntegerField(default=0, help_text='Montant total à payer (FCFA)'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='public_token',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
    ]
