# Generated by Django 6.0.1 on 2026-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_alter_inscription_amount_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='amount_due',
            field=models.PositiveIntegerField(help_text='Montant total à payer (FCFA)'),
        ),
    ]
