# Generated by Django 6.0.1 on 2026-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0006_alter_inscription_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='amount_due',
            field=models.PositiveIntegerField(default=0, help_text='Montant total à payer pour cette inscription (FCFA)'),
        ),
    ]
