# Generated by Django 6.0.1 on 2026-02-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0007_alter_inscription_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='amount_due',
            field=models.PositiveIntegerField(help_text='Montant total à payer pour cette inscription (FCFA)'),
        ),
    ]
