# Generated by Django 6.0.1 on 2026-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0008_alter_inscription_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='access_code',
            field=models.CharField(blank=True, help_text='Code d’accès privé au dossier', max_length=20),
        ),
    ]
