# Generated by Django 6.0.1 on 2026-02-07 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='admissions__last_na_27a2d0_idx'), models.Index(fields=['email'], name='admissions__email_906b31_idx')],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('under_review', 'En étude'), ('incomplete', 'Dossier incomplet'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='submitted', max_length=20)),
                ('motivation', models.TextField(blank=True, help_text='Lettre ou texte de motivation du candidat')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='formations.programme')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.candidate')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admissions/documents/')),
                ('is_valid', models.BooleanField(help_text="Validé par l'administration", null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formations.requireddocument')),
            ],
            options={
                'ordering': ['uploaded_at'],
                'unique_together': {('application', 'document')},
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='admissions__status_cd8e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['submitted_at'], name='admissions__submitt_f17493_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'programme')},
        ),
    ]
