# Generated by Django 6.0.1 on 2026-02-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin')], max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Mali', max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('under_review', 'En cours d’analyse'), ('to_complete', 'À compléter'), ('accepted', 'Acceptée'), ('accepted_with_reserve', 'Acceptée sous réserve'), ('rejected', 'Refusée')], default='submitted', max_length=30)),
                ('admin_comment', models.TextField(blank=True, help_text='Commentaire interne (non visible par le candidat)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='formations.programme')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidatureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='candidatures/documents/')),
                ('is_valid', models.BooleanField(default=False, help_text='Validé par l’administration')),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.candidature')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formations.requireddocument')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['status'], name='admissions__status_c3c8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['programme'], name='admissions__program_87ac59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidaturedocument',
            unique_together={('candidature', 'document_type')},
        ),
    ]
