# Generated by Django 6.0.1 on 2026-02-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='entry_year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Année d’entrée dans le programme (1 = première année)'),
        ),
    ]
