# Generated by Django 6.0.1 on 2026-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['phone'], name='admissions__phone_2480fb_idx'),
        ),
    ]
